#!/bin/sh

# Title: SSHFS Manager
# Description: bash script for connect remote server via sshfs and standard ssh config
# Author: Michael Berner
# Project URL: https://github.com/bernermic/sshfsconnect
# Version 0.0.1
# Licence: GNU General Public License v3.0



command -v sshfs >/dev/null 2>&1 || { echo >&2 "I require sshfs but it's not installed.  Aborting."; exit 1;}
command -v zenity >/dev/null 2>&1 || { echo >&2 "I require zenity but it's not installed.  Aborting."; exit 1;}
test $(grep "^user_allow_other" /etc/fuse.conf) || { echo >&2 "I require user_allow_other in /etc/fuse.conf.  Aborting."; exit 1;}
test $(grep "^Host " ~/.ssh/config | wc -l) -gt 0 || { echo >&2 "I require a usable Host in ~/.ssh/config.  Aborting.";}

server=$(zenity --list --radiolist --column Select --column Server echo $(grep "^Host " ~/.ssh/config | awk '{print $2" FALSE"}'))
test -z $server && { echo >&2 "No server selected.  Aborting."; exit 1;}
mkdir -p ~/mount/$server
sshfs $server:/ ~/mount/$server -o auto_cache,kernel_cache,reconnect,transform_symlinks,follow_symlinks,default_permissions,hard_remove,allow_other
